<?php
unset(
    $_SESSION["err-id"],
    $_SESSION["err-number"],
    $_SESSION["err-sei"],
    $_SESSION["err-mei"],
    $_SESSION["err-pass"],
    $_SESSION["err-pass_conf"],
    $_SESSION["err-title"],
    $_SESSION["err-contents"],
    $_SESSION["err-name"],
    $_SESSION["log_out"],

    $_SESSION["err-year"],
    $_SESSION["err-month"],
    $_SESSION["err-day"],
    $_SESSION["err-work_type"],
    $_SESSION["err-s_time"],
    $_SESSION["err-s_minutes"],
    $_SESSION["err-e_time"],
    $_SESSION["err-e_minutes"],
    $_SESSION["err-break_time"],
    $_SESSION["err-break_minutes"],
    $_SESSION["err-midnight_time"],
    $_SESSION["err-midnight_minutes"],
    $_SESSION["err-work_time"],
    $_SESSION["err-work_minutes"],
    $_SESSION["err-over_time"],
    $_SESSION["err-over_minutes"],
    $_SESSION["err-old_pass"],

    $_SESSION["break_time"],
    $_SESSION["break_minutes"],
    $_SESSION["err-over_time_reason"],
    $_SESSION["key"]
);
?>